services:

  db:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - private

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASS
      PGADMIN_LISTEN_PORT: 5050
    labels:
      - traefik.enable=true
      - traefik.http.services.pgadmin.loadbalancer.server.port=5050
      - traefik.http.routers.pgadmin-http.entrypoints=http
      - traefik.http.routers.pgadmin-http.rule=Host(`server.kit-api.com`)
      - traefik.docker.network=public
    networks:
      - public
      - private
    depends_on:
      - db

  app:
    container_name: app
    restart: always
    build: .
    command: bash -c "uvicorn kitapi.main:app --host 0.0.0.0 --port 80"
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`kit-api.com`)
      - traefik.docker.network=public
    networks:
      - public
      - private
    depends_on:
      - db

networks:
  public:
    external: true
  private:
    external: false

volumes:
  postgres_data:
