services:

  traefik:
    container_name: proxy
    image: traefik:v2.5
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - public-certificates:/certificates
    command:
      - --log
      - --accesslog
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=admin@kit-api.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    networks:
      - public

networks:
  public:
    external: true

volumes:
  public-certificates:
