services:

  db:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - $DB_PORT
    networks:
      - private

  app:
    container_name: app
    restart: always
    build: .
    command: bash -c "uvicorn kitapi.main:app --host 0.0.0.0 --port $HTTP_PORT"
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=$HTTP_PORT
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`$DOMAIN`, `www.$DOMAIN`)
      - traefik.docker.network=public
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`$DOMAIN`, `www.$DOMAIN`)
      - traefik.http.routers.app-https.tls=true
      - traefik.http.routers.app-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.ratelimit.ratelimit.average=$RATELIMIT_AVG
      - traefik.http.middlewares.ratelimit.ratelimit.burst=$RATELIMIT_BURST
      - traefik.http.middlewares.ratelimit.ratelimit.period=$RATELIMIT_PER
      - traefik.http.middlewares.ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=$IPSTRATEGY_DEPTH
      - traefik.http.routers.app-http.middlewares=https-redirect,ratelimit
      - traefik.http.routers.app-https.middlewares=ratelimit
    networks:
      - public
      - private
    depends_on:
      - db

networks:
  public:
    external: true
  private:
    external: false

volumes:
  postgres_data:
