services:

  traefik:
    container_name: proxy
    image: traefik:v2.5
    restart: always
    ports:
      - 80:$HTTP_PORT
      - 443:$HTTPS_PORT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - public-certificates:/certificates
    command:
      - --log
      - --accesslog
      - --entrypoints.http.address=:$HTTP_PORT
      - --entrypoints.https.address=:$HTTPS_PORT
      - --certificatesresolvers.le.acme.email=$SSL_ADMIN_EMAIL
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    networks:
      - public

networks:
  public:
    external: true

volumes:
  public-certificates:
