services:

  traefik:
    container_name: proxy
    image: traefik:v2.5
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --accesslog
      - --entrypoints.http.address=:80
      - --log
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    networks:
      - public

networks:
  public:
    external: true
