name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Check types
        run: python -m pyright

      - name: Check formatting
        run: python -m black kitapi --check

      - name: Check imports
        run: isort kitapi -cq
